### PR TITLE
fix: fixed profile information components structure

### LINKED ISSUE #210: Profile information styles
Reestructure profile information styles to match on different screen sizes

### PR DESCRIPTION
**Pull request by flobarreto**
closes #210

### CODE REVIEW

**Comment by LautaroPetaccio** [comment]
I was checking the site and it seems that it doesn't match what we wanted to do.
Screenshot 2023-08-17 at 18 02 18.
The idea was to have rows instead of two columns, having the first row the name and the actions.
The styles on mobile seem to have shifted down from where they currently are:
Screenshot 2023-08-17 at 18 03 58

File: src/components/ProfileInformation/ProfileInformation.tsx [hunk 1]
```diff
@@ -200,6 +160,54 @@ const ProfileInformation = (props: Props) => {
           </div>
         )}
       </div>
+    ),
+    []
```
Comment (LautaroPetaccio) [inline src/components/ProfileInformation/ProfileInformation.tsx:164]: Remember to add the variables the function depend on here.
Things like `avatar`, `profileAddress`, `avatarName` and others are important and should be here.

**Review by LautaroPetaccio — APPROVED** [review]
