### PR TITLE
fix: empty message on profile overview

### LINKED ISSUE #97: Message on non-equipped wearables in other profile's view
- **What is happening?**
    - When I navigate to a user's profile and the profile is not equipped with collectibles it should display an empty message for other profiles and not for my profile 
    

    
- **What should happen?**
    - The message should be "Danielitox doesn't have any collectible wearables yet." and the "go to marketplace" button should not be displayed 
    

- **How did this happen?**
    - navigating to 'https://profile.decentraland.zone/accounts/0xA4f689625F6F51AdF691a64D38772BE8509087d2' profile with my address (0xd4fEC88A49EB514e9347eC655D0481D8483a9AE0)

### PR DESCRIPTION
**Pull request by flobarreto**
closes #97

### CODE REVIEW

File: src/components/Overview/Overview.tsx [hunk 1]
```diff
@@ -39,11 +41,17 @@ const Overview = (props: Props) => {
       ) : (
         <div className={classNames(styles.emptyItems, isTabletAndBelow && styles.emptyItemsMobile)} data-testid="overview-empty">
           <img src={shirt} className={styles.emptyIcon} />
-          <span className={styles.title}>{t('overview.start_dressing')}</span>
-          <span>{t('overview.get_collectibles')}</span>
-          <Button inverted as="a" href={MARKETPLACE_URL} target="_blank">
-            {t('overview.go_to_marketplace')}
-          </Button>
+          <span className={styles.title}>
+            {isLoggedInProfile ? t('overview.start_dressing') : `${profile && profile?.avatars[0].name} ${t('overview.no_collectibles')}`}
```
Comment (LautaroPetaccio) [inline src/components/Overview/Overview.tsx:45]: If the profile does not exist or does not have a name, it will result on it being undefined, which will write `undefined`. What if we use the `getAvatarName` function?
```suggestion
            {isLoggedInProfile ? t('overview.start_dressing') : `${profile && profile?.avatars[0].name} ${t('overview.no_collectibles')}`}
```

**Review by LautaroPetaccio — CHANGES_REQUESTED** [review]

**Review by LautaroPetaccio — APPROVED** [review]
